#!/usr/bin/env node
// Generate globals.d.ts for the type-checker (B201). The shared scripts run in ONE global scope, but
// TypeScript's checkJs treats each file's top-level `const`/`let` as file-local — so without help, a
// function in parsers.js referencing `mod`/`SKILLS`/`blankMonster` (defined in another file) trips
// "Cannot find name". This mirrors what eslint.config.js does for no-undef: parse every OTHER shared
// file's top-level declarations and emit `declare const NAME: any;` so tsc knows the ambient globals.
// Self-maintaining: re-run (npm run typecheck does this automatically) and the list stays correct.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import * as espree from "espree";

const here = join(dirname(fileURLToPath(import.meta.url)), "..");
// Every shared script EXCEPT the file we actually type-check (parsers.js) — its own declarations are real,
// not ambient, so declaring them here too would collide ("Cannot redeclare block-scoped variable").
const SOURCE_FILES = ["data.js", "core.js", "forge.js", "engine.js", "bestiary.js", "adventures.js", "roster.js", "combat.js", "seed.js", "app.js"];

const names = new Set();
for (const file of SOURCE_FILES) {
  let ast;
  try { ast = espree.parse(readFileSync(join(here, file), "utf8"), { ecmaVersion: "latest", sourceType: "script", loc: false }); }
  catch { continue; }
  for (const node of ast.body) {
    if (node.type === "FunctionDeclaration" && node.id) names.add(node.id.name);
    else if (node.type === "ClassDeclaration" && node.id) names.add(node.id.name);
    else if (node.type === "VariableDeclaration") {
      for (const d of node.declarations) {
        if (d.id.type === "Identifier") names.add(d.id.name);
        else if (d.id.type === "ObjectPattern") for (const p of d.id.properties) { if (p.value && p.value.type === "Identifier") names.add(p.value.name); }
        else if (d.id.type === "ArrayPattern") for (const e of d.id.elements) { if (e && e.type === "Identifier") names.add(e.name); }
      }
    }
  }
}

const lines = [
  "// AUTO-GENERATED by scripts/gen-globals.mjs — do not edit by hand.",
  "// Ambient declarations for the cross-file globals of the shared-scope scripts, so `tsc --checkJs`",
  "// resolves them. Regenerated by `npm run typecheck`. See scripts/gen-globals.mjs.",
  ...[...names].sort().map((n) => `declare const ${n}: any;`),
  "",
];
writeFileSync(join(here, "globals.d.ts"), lines.join("\n"));
console.log(`globals.d.ts: ${names.size} ambient globals declared.`);
